home/urls.py
from django.contrib import admin
from django.urls import include,path
from .views import index

urlpatterns = [
    path('', index, name='index')
]

sign_up/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls import url
from .views import signup

urlpatterns = [
    path('', signup, name='signup'),
]

tp/urls.py
from django.contrib import admin
from django.urls import path,include
from donatepage import urls
import home.urls as home
import sign_up.urls as sign_up
import program_detail.urls as program_detail
from News.views import news, generate_article_page
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'),namespace='home')),
    path('donate/', include(('donatepage.urls', 'donate'), namespace='donate')),
    path('News/', include(('News.urls','news'),namespace='news')),
    path('signup/', include(('sign_up.urls', 'sign_up'), namespace='signup')),
    path('program/', include(('program_detail.urls','program_detail'), namespace='program_detail'))
]

urlpatterns += staticfiles_urlpatterns()

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from sign_up.views import signup 

# Create your views here.
response={}

def index(request):
    return render(request,'index.html',response)

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{% block title %}My Website{% endblock %}</title>

        <!-- Custom styles for this template -->
        
        <link href='https://fonts.googleapis.com/css?family=Karla' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>
        <link href="{% static 'css/stylehome.css' %}" rel="stylesheet" type="text/css">        
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/article-style.css' %}" rel="stylesheet">     
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />

        
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>   
        <script src="main.js"></script>

        <!-- Materialize CSS -->
            <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

        
        

    </head>

    <body>        
        <header>
            {% include "navbar.html" %}
        </header>
        
        
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
        
        <footer>
        </footer>
        
    </body>
    
</html>

home/templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}


    <div class="bg" style="padding-bottom: 500px">
		<div style="padding-left:20px;">
	<link href='https://fonts.googleapis.com/css?family=Karla' rel='stylesheet'>

	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />

	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>
	
	<link href="{% static 'css/stylehome.css' %}" rel="stylesheet" type="text/css">
    
	<meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tugas 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script>
	$(document).ready(function(){
	  // Add smooth scrolling to all links
	  $("a").on('click', function(event) {

	    // Make sure this.hash has a value before overriding default behavior
	    if (this.hash !== "") {
	      // Prevent default anchor click behavior
	      event.preventDefault();

	      // Store hash
	      var hash = this.hash;

	      // Using jQuery's animate() method to add smooth page scroll
	      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
	      $('html, body').animate({
	        scrollTop: $(hash).offset().top
	      }, 800, function(){
	   
	        // Add hash (#) to URL when done scrolling (default click behavior)
	        window.location.hash = hash;
	      });
	    } // End if
	  });
	});
	</script>

    <style type="text/css">
    * {
    box-sizing: border-box;
	}

	a{
		font-family: 'Ubuntu';
	}


	/* CSS WHat We Do Create three equal columns that floats next to each other */
	.columnDonate {
	    float: left;
	    width: 33.33%;
	    height: 300px; /* Should be removed. Only for demonstration */
	    padding: 10px
	}

	/* Clear floats after the columns */
	.row:after {
	    content: "";
	    display: table;
	    clear: both;
	    text-align: center;
	}

	/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
	@media screen and (max-width: 600px) {
	    .columnDonate {
	        width: 100%;
	    }
	}
    </style>

</head>

<body>
	{% block content %}
    <div class="bg" style="padding-bottom: 500px">
		<div>
			<p style="color: #47525E; text-align: center; padding-top: 30px; font-family: 'Karla'; font-size: 20px">Yayasan Sinar Perak</p> 
			<h1 style="font-family: 'Bree Serif'; text-align: center;">Give a little. Change lot</h1>
			<div class="container" style="max-width: 150px;">
				<a class="button" href="#section2" type="submit" style="text-align: center; width: 120px">Learn more</a></div>
		</div>
	</div>


	<div class="main" id="section2"><section>
		<h1 style="padding-top: 50px; padding-bottom: 30px; text-align:center; font-family: 'Ubuntu'">About Us</h1>
		<div class="row" style="max-width: 800px; margin: auto;" >	
			<div class="columntxt" style="padding-right: 25px">
				<p>Lorem ipsum dolor sit amet, consectetur adipi elit. Cras mollis ligula mauris, vitae porttitor nunc maximus Integer fringilla place acLorem ipsum dolor sit amet, consectetur adipiscing elit.  
				Lorem ipsum dolor sit amet, consectetur adipi elit. Cras mollis ligula mauris, vitae porttitor nunc maximus Integer fringilla place acLorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
				<p>Etiam ut erat et nisi pulvinar accumsan. Curabitur imperdiet at sem vel elementum.</p>
			</div>
			<div class="columntxt">
				<img src="https://marvel-live.freetls.fastly.net/canvas/2018/10/5d0b0d929ceb4946a6561a84cd1be213?quality=95&fake=.png" alt="SinarPerak" style="float:center; width: 100%;">	
			</div>
		</div>
	</section></div>


	<div class="main" id="section3">
  	<section>
	<h2 style="font-family: 'Ubuntu'; text-align: center; padding-top: 50px; padding-bottom: 20px; margin: auto; ">What We Do</h2>
	<p style="text-align: center; padding-left: 200px; padding-right: 200px;">We create events aiming to pear to the voice for children and gather for support. 
	Please update with our events and confirm you presence.</p>

	<div class="row" style="text-align: center; padding-left: 150px; padding-right: 150px">
	  <div class="columnDonate" >
	  	<img src="https://marvel-live.freetls.fastly.net/canvas/2018/10/d1c335fbb86d439f9e108079b6468706?quality=95&fake=.png" alt="Education" style="float:center; width: 200px; height: 200px;">
	    <h4>Donate For Education</h2>
	    <p>Some text..</p>
	  </div>
	  <div class="columnDonate" style="background-color:white;">
	  	<img src="https://marvel-live.freetls.fastly.net/canvas/2018/10/09516ff81268487186e847b6a52110f3?quality=95&fake=.png" alt="Food" style="float:center; width: 200px; height: 200px;">
	    <h4>Donate For Food</h2>
	    <p>Some text..</p>
	  </div>
	  <div class="columnDonate" style="background-color:white;">
	  	<img src="https://marvel-live.freetls.fastly.net/canvas/2018/10/f5f910f705074b9f869f1e37654f6341?quality=95&fake=.png" alt="Water" style="float:center; width: 200px; height: 200px;">
	    <h4>Donate For Water</h2>
	    <p>Some text..</p>
	  </div>

	 	<div class="container" style="max-width: 400px">
	  	<a href="{% url 'signup:signup' %}" type="submit" class="button" style="font-family: 'Ubuntu'; color: white; background-color: #43C6E5; border-style: none; padding: 10px; margin-top: 50px; margin-bottom: 50px; width: 200px">Join us today!</a>
	  	</div>
	 	

	</div>
	</section></div>



</body>
</html>
{% endblock %}

home/templates/navbar.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <div class="header">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <a href="{% url 'signup:signup' %}" class="logo" style="float: right">Sign Up</a>
    <div class="header-left">
      <a href="{% url 'home:index' %}">Home</a>
      <a href="{% url 'news:index' %}">News</a>
    </div>
  </div>
</html>