donatepage/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url
from .views import index_donate_confirm, show_form
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "Donate"
urlpatterns = [
    path('', show_form, name='donate'),
    path('addDonasi', index_donate_confirm, name='adddonasi'),
    url(r'^addDonasi',index_donate_confirm, name='addDonasi'),
]

urlpatterns += staticfiles_urlpatterns()

tp/urls.py
from django.contrib import admin
from django.urls import path,include
from donatepage import urls
import home.urls as home
import sign_up.urls as sign_up
import program_detail.urls as program_detail
from News.views import news, generate_article_page
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'),namespace='home')),
    path('donate/', include(('donatepage.urls', 'donate'), namespace='donate')),
    path('News/', include(('News.urls','news'),namespace='news')),
    path('signup/', include(('sign_up.urls', 'sign_up'), namespace='signup')),
    path('program/', include(('program_detail.urls','program_detail'), namespace='program_detail'))
]

urlpatterns += staticfiles_urlpatterns()

donatepage/models.py
from django.db import models
from datetime import datetime, date
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


# Create your models here.
def validate_positive(value):
    if value < 0 and value % 1 != 0 :
        raise ValidationError(
            _('%(value)s is not positive integer number'),
            params={'value': value},
        ) 

class DonateModel(models.Model):
    name = models.CharField(max_length = 3000)
    email = models.EmailField(max_length = 3000)
    nominal = models.IntegerField(validators=[validate_positive])
    message = models.TextField(max_length = 3000)
    password = models.CharField(max_length = 3000)
    checkbox = models.BooleanField()

    def ___str__(self):
        return self.name

    

donatepage/forms.py
from django import forms
from .models import DonateModel

class DonateForm(forms.ModelForm):
    class Meta:
        model = DonateModel
        fields = ('name','email','nominal','password','message','checkbox',)

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','type': 'text','placeholder':'Your name'}),
            'email': forms.TextInput(attrs={'class': 'form-control','type':'text','placeholder':'Email'}),
            'nominal': forms.NumberInput(attrs={'class': 'form-control','placeholder':'Amount of donation'}),
            'password': forms.PasswordInput(attrs={'class':'form-control','type':'password','placeholder':'Password'}),
            'message': forms.Textarea(attrs={'class': 'form-control','type': 'text','placeholder':'Write something nice','rows':'3','cols':'10'}),
            'checkbox': forms.CheckboxInput(),
        }

donatepage/views.py
from django.shortcuts import render
from .forms import DonateForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import DonateModel
from project.models import Project

# Create your views here.
response = {}

def show_form(request):
    donasi = DonateModel.objects.all()
    form = DonateForm()
    html = 'donate_page.html'
    return render(request, html, {'donasi':donasi, 'form':form})

def index_donate_confirm(request, tittle):
    project = Project.objects.get(pk=pk)
    if request.method == 'POST':
        form = DonateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Donate:donate'))
        else:
            form = DonateForm()
            return render(request, 'donate_page.html', {'form' : form})
    
    form = DonateForm()
    return render(request, 'donate_page.html', {'form':form, 'project':project})

def index_donate_cancel(request):
    return render(request, 'index.html')

donatepage/templates/donate_page.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Donate Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/donatepage.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-color:lightgray;">

<div class="container">
        <form id='form' method="POST" action="{% url 'Donate:adddonasi' %}">
            {% csrf_token %}
            <h1 class="nama_project">Donate to {{ project.title }}</h1>
            <div class="form-group">
            {% for field in form %}
            <div class="add_margin">
                {% if field.name == 'checkbox' %}
                    {{ field.as_widget }} <label>{{ 'I want donate anonymously' }}</label>
                {% else %}
                    {{ field.as_widget }}
                {% endif %}
            </div>
            {% endfor %}
            </div>
            <div class="col-12">
                <button id="button1" type="submit" class="btn btn-info btn-md col-md-5"><b>Confirm</b></button>
                <a class="col-md-2"></a>
                <button id="button2" type="cancel" class="btn btn-danger btn-md col-md-5"><a href="{% url 'index' %"><b>Cancel</b></a></button> 
            </div>
        </form>
    </div>
</div>
        
</body>
</html>